inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara

require:
  - rubocop-rails

Metrics/MethodLength:
  Max: 50

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
