inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara

require:
  - rubocop-rails

Metrics/BlockLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

AllCops:
    SuggestExtensions: false
